[package]
name = "assignment-tracker-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5.2"
axum = "0.7.3"
axum-macros = "0.4.1"
bytes = "1.5.0"
chrono = { version = "0.4.31", features = ["serde"] }
dotenvy = "0.15.7"
fern = { version = "0.6.2" }
log = "0.4.20"
mime = "0.3.17"
owo-colors = "4.0.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_path_to_error = "0.1.15"
sqlx = { version = "0.7.3", features = [
    "runtime-tokio",
    "postgres",
    "macros",
    "chrono",
    "uuid",
] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors"] }
tower-sessions = { version = "0.9.1", features = [
    "postgres-store",
    "deletion-task",
] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }
