// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Assignment { id: string, course_id: string, name: string, out_date: string, due_date: string, progress: number, }