[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
fern = { version = "0.7" }
dotenvy = "0.15"

tokio = { workspace = true }
log = { workspace = true }
chrono = { workspace = true }

webserver = { workspace = true }
