[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"

tokio = { workspace = true }
chrono = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = "0.3"
tracing-appender = "0.2"

webserver = { workspace = true }
